#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

while [[ $# -gt 0 ]]; do
    case "$1" in
        -u)
            shift 2
            ;;
        --)
            shift
            exec "$@"
            ;;
        *)
            shift
            ;;
    esac
done

printf 'fake runuser: missing command after --\n' >&2
exit 1
