#!/usr/bin/env bash

set -o nounset

mailbox=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -z)
            shift
            ;;
        -m)
            mailbox="$2"
            shift 2
            ;;
        -t)
            shift 2
            ;;
        *)
            break
            ;;
    esac
done

command_name="${1:-}"
shift || true

case "$command_name" in
    gms)
        printf '123\n'
        ;;
    getRestURL)
        printf 'fake mailbox for %s\n' "$mailbox" | gzip -c
        ;;
    postRestURL)
        gzip -t "${2:?archive path is required}"
        if [[ "${FAKE_IMPORT_RC:-0}" != "0" ]]; then
            exit "$FAKE_IMPORT_RC"
        fi
        ;;
    *)
        printf 'Unsupported zmmailbox command: %s\n' "$command_name" >&2
        exit 1
        ;;
esac
